move resources to standard Maven location
spdx/Spdx-Java-Library pull request #186
Opened 2023-07-08 21:52 UTC by hboutemy

2023-07-10 23:35 UTC, goneall requested changes
The following references to the resources directory needs to be updated with the new location:

- [ListedLicenses reference to properties file](https://github.com/spdx/Spdx-Java-Library/blob/4666b452a5d09af9847ee3045fe4ea6b946ed432/src/main/java/org/spdx/library/model/license/ListedLicenses.java#L48)
- [ListedReferenceTypes reference to properties file](https://github.com/spdx/Spdx-Java-Library/blob/4666b452a5d09af9847ee3045fe4ea6b946ed432/src/main/java/org/spdx/library/referencetype/ListedReferenceTypes.java#L49)
- [ListedLicenseLocalStore reference to license JSON files](https://github.com/spdx/Spdx-Java-Library/blob/4666b452a5d09af9847ee3045fe4ea6b946ed432/src/main/java/org/spdx/storage/listedlicense/SpdxListedLicenseLocalStore.java#L34)

2023-07-10 23:35 UTC, goneall commented on src/main/resources/resources/licenses.properties
@hboutemy - Did you intend for the licenses.properties to be moved under a second directory `.../resources/resources`?

2023-09-14 20:21 UTC, pmonks commented
@goneall I wonder if this is related to our separate conversation about the `log4j2-test.xml` file not functioning in my #193 fork?  :thinking:

2024-03-07 02:19 UTC, goneall commented
I'm going to close this due to the compatibility issues related to this pull request.  I do appreciate the suggestion to move this to a more compliant Maven location for the resources.

2024-03-07 02:19 UTC, closed without merging